site_name: Archiving Wiki (Beta)
site_description: Wiki
site_author: Sekkon
site_url: https://wiki.yami-s.com/

copyright: Copyright &copy; 2023 Sekkon

theme:
  language: pt-BR
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - offline
  - search