site_name: Archiving Wiki (Beta)
site_description: Wiki
site_author: Sekkon
site_url: https://wiki.yami-s.com/

copyright: Copyright &copy; 2024 Sekkon

theme:
  language: pt-BR
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  features:
    - navigation.tabs
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - footnotes
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
#  - offline
  - search
  - table-reader
  - privacy

nav:
  - Home: index.md
  - Sistema:
    - MAS: Sistema/MAS.md
    - Office: Sistema/Office.md
    - Ventoy: Sistema/Ventoy.md
    - Windows 10 Enterprise LTSC: Sistema/Windows 10 Enterprise LTSC.md
  - DRM:
    - L3 Android Studio: DRM/L3 Android Studio.md
  - Encode:
    - VapourSynth: Encode/VapourSynth.md